
"use client"
// import type { Metadata } from "next";
import {  Nunito, Rosarivo,Noto_Sans_Old_Persian } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "sonner"
import { NextAuthProvider } from "@/components/providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import { RecoilRoot } from "recoil";
const inter =  Nunito({subsets: ["latin"],weight:"400" })


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <QueryClientProvider client={queryClient}>
      <Suspense>
      <RecoilRoot>
      <html lang="en" className="dark" >
        <body className={`flex justify-center bg-neutral-900 items-center w-full ${inter.className}`}>
          <NextAuthProvider>
            <div className="flex max-w-[1050px] w-full gap-x-4  p-2 h-full justify-center items-center flex-col">

              <div className="flex py-4  min-h-[90vh] w-full flex-col justify-start items-center  ">
                <Header />
                {children}
              </div>

              <Footer/>
            </div>
          </NextAuthProvider>
          <Toaster />
        </body>
      </html>
      </RecoilRoot>
      </Suspense>
    </QueryClientProvider>
  );
}
